# Generated by Django 3.0.5 on 2020-04-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postTitle',
            field=models.TextField(null=True),
        ),
    ]
