# Generated by Django 3.0.5 on 2020-04-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_posttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postUrl',
            field=models.TextField(null=True),
        ),
    ]
