# Generated by Django 3.0.5 on 2020-04-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField(null=True)),
                ('studentName', models.CharField(max_length=20, null=True)),
                ('studentPassword', models.CharField(max_length=50, null=True)),
                ('studentSubject', models.TextField(null=True)),
                ('studentTimetable', models.TextField(null=True)),
            ],
        ),
    ]
